# Site settings
title: 童建的博客
email: tstj9022@gmail.com
description: Jay Tong’s home #李贤俊:D博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaytong.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  jaytong90

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 童建
  email: 
  link: 
  weibo: 
  github: http://github.com/LxlanJ
title: Jian's Blog                          #自定义常量

# avatar头像及Favicon
avatar: http://i0.kym-cdn.com/photos/images/original/000/933/971/6ce.gif
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: lxlanj
